name: lint
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0
    - name: Run golangci-lint
      run: make lint
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.18.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run go test
        run: go test -cover
  release:
      name: semantic version tagging on merge to master branch
      runs-on: ubuntu-latest
      needs: [lint, test]
      if: github.event.pull_request.merged    
      steps:
        - name: Tag
          uses: K-Phoen/semver-release-action@master
          with:
            release_branch: master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}